version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    # network_mode: host
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1884:1883
